language: ruby
cache: bundler
env:
  - GOOGLE_CLIENT_ID=REDACTED GOOGLE_CLIENT_SECRET=REDACTED TRELLO_DEVELOPER_PUBLIC_KEY=REDACTED TRELLO_MEMBER_TOKEN=REDACTED GITHUB_PERSONAL_ACCESS_TOKEN=REDACTED NOTIFY_API_KEY=REDACTED

